apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    resources:
      requests:
        cpu: "500m" # Min 0.5 CPU
        memory: "128Mi" # Min 128 MB of memory
      limits:
        cpu: "1000m" # Max 1 CPU
        memory: "256Mi" # Max 256 MB of memory
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP